### ISSUE TITLE
ModuleNotFoundError: No module named 'kaolin.graphics'

### ISSUE THREAD

**Issue by ujjawalcse** [NikolaZubic/2dimageto3dmodel#2]
Pascal 3D+ dataset with 4722 images is successfully loaded.

`Traceback (most recent call last):
  File "main.py", line 149, in <module>
    from rendering.renderer import Renderer
  File "/home/ujjawal/my_work/object_recon/2d3d/code/rendering/renderer.py", line 1, in <module>
    from kaolin.graphics.dib_renderer.rasterizer import linear_rasterizer
ModuleNotFoundError: No module named kaolin.graphics`

I also downloaded the graphics folder from here https://github.com/NVIDIAGameWorks/kaolin/tree/e7e513173bd4159ae45be6b3e156a3ad156a3eb9 and tried to place in the graphics folder in the kaolin folder locally and here is the error 
`Traceback (most recent call last):
  File "main.py", line 149, in <module>
    from rendering.renderer import Renderer
  File "/home/ujjawal/my_work/object_recon/2d3d/code/rendering/renderer.py", line 1, in <module>
    from kaolin.graphics.dib_renderer.rasterizer import linear_rasterizer
  File "/usr/local/lib/python3.6/dist-packages/kaolin-0.9.0-py3.6-linux-x86_64.egg/kaolin/graphics/__init__.py", line 2, in <module>
  File "/usr/local/lib/python3.6/dist-packages/kaolin-0.9.0-py3.6-linux-x86_64.egg/kaolin/graphics/nmr/__init__.py", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/kaolin-0.9.0-py3.6-linux-x86_64.egg/kaolin/graphics/nmr/rasterizer.py", line 30, in <module>
ImportError: cannot import name rasterize_cuda `

**Comment by NikolaZubic** [comment]
There are a lot of problems that can occur. Most users emailed us and were satisfied. Everything worked. It is recommended to use Linux. We cannot guarantee that this project will work on other operating systems because of the Kaolin and other third-party modules. Also, do not forget to check your CUDA version and update everything. If you have that problem, it is associated with Kaolin installation, not with this project.

**Comment by ricklentz** [comment]
@ujjawalcse You may want to double-check that you used the correct branch of Kaolin.

@NikolaZubic Great work!  I did a PR to add a line to your install docs after the `cd kaolin` step: `git checkout e7e513173b`. It will be a clear reminder to others not to forget to switch Kaolin branches before installing (else, they will get the above "ModuleNotFoundError: No module named kaolin.graphics" error).

**Comment by ujjawalcse** [comment]
Thanks, @ricklentz,
yaa sure I'll try it.

**Comment by Praveenk8051** [comment]
@ujjawalcse were you able to solve this error ?

**Comment by lw0210** [comment]
> Thanks, @ricklentz, yaa sure I'll try it.

Have you reproduced the paper？

**Comment by lw0210** [comment]
Thanks for your help,you are so enthusiastic!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NikolaZubic/2dimageto3dmodel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月31日(星期天) 上午6:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NikolaZubic/2dimageto3dmodel] ModuleNotFoundError: No module named 'kaolin.graphics' (#2)





 
Closed #2.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
